version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm run-script build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./ s3://tester403
      - aws cloudfront create-invalidation --distribution-id E2V33APWSQZ5SX --paths "/*";
