version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm install
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync .dist s3://tester403
      - aws cloudfront create-invalidation --distribution-id E2V33APWSQZ5SX --paths "/*";
